version: '3.8'

services:
  screener:
    build:
      context: ./engine
      dockerfile: Dockerfile
    container_name: sahamscreen-screener
    volumes:
      - ./engine/data:/app/data
    env_file:
      - .env
    restart: always
