/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary": "#002e6a",
        "inverse-surface": "#dfe2ef",
        "secondary": "#4ae176",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#c2c6d6",
        "on-primary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#004395",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#dfe2ef",
        "on-secondary-fixed": "#002109",
        "inverse-primary": "#005ac2",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error": "#690005",
        "secondary-fixed": "#6bff8f",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003915",
        "surface": "#0f131c",
        "on-secondary-fixed-variant": "#005321",
        "error": "#ffb4ab",
        "primary": "#adc6ff",
        "primary-container": "#4d8eff",
        "surface-container": "#1c1f29",
        "surface-container-low": "#181b25",
        "tertiary": "#ffb95f",
        "secondary-container": "#00b954",
        "on-surface": "#dfe2ef",
        "surface-bright": "#353943",
        "inverse-on-surface": "#2c303a",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-high": "#262a34",
        "surface-tint": "#adc6ff",
        "surface-container-lowest": "#0a0e17",
        "surface-dim": "#0f131c",
        "on-tertiary": "#472a00",
        "background": "#0f131c",
        "outline": "#8c909f",
        "on-tertiary-container": "#3e2400",
        "tertiary-container": "#ca8100",
        "on-secondary-container": "#004119",
        "surface-container-highest": "#31353f",
        "outline-variant": "#424754"
      },
      "fontFamily": {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
